"""The model lifecycle: when to retrain, a challenger, a promotion gate, and a rollback.

The monitoring jobs (`monitoring.py`) each produce a signal on their own clock. This module is
the one place the two are read together, and the reading is asymmetric on purpose: realised
decay on a mature batch is the primary trigger, because it is the failure itself; drift held
across consecutive cycles is a secondary, earlier trigger, because it is a reason to suspect the
failure before the labels can show it. One cycle of drift is not a trigger. ADR 0036, ADR 0038.

A challenger is fitted on a recent window through the stage 3 pipeline and the stage 6 model,
the same code with the same decisions, under the same train-only guard with its boundary moved
to the window's end (`data_loader.training_boundary`). It is gated against the champion on a
held-out window the fit never saw, paired on identical resamples, and promoted only when its
advantage clears a margin above the noise stage 6 measured. Promotion moves the registry alias
the service loads; the alias it moved from is kept, and rollback moves it back.
"""

from __future__ import annotations

import contextlib
import time
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import numpy.typing as npt
import pandas as pd

from fraud_platform import (
    cleaning,
    config,
    data_loader,
    encoders,
    evaluation,
    features,
    modelling,
    prepare,
    serving,
)

# The promotion margin. Stage 6 measured the noise on the primary metric as paired 95 percent
# bootstrap half-widths of the test PR-AUC, 1,000 resamples, seed 42, every pair of its ten
# models (reports/metric_variance.json, block `noise_band`, regenerated by `make train`):
#
#     widest paired half-width by row    0.0172   logistic_regression__smote vs xgboost__smote
#     widest paired half-width by card   0.0592   logistic_regression__class_weight vs random_forest__none
#
# The card resample draws whole entities and respects the card-level labels ADR 0001 measured,
# and it is the wider, so it is the band. A point advantage at least as large as the widest
# half-width has a lower bound at or above zero for every pair stage 6 measured, which is what
# "above the noise" has to mean for a margin fixed before any challenger exists. 0.0592 rounded
# up at the second decimal:
PROMOTION_MARGIN = 0.06

# The decay tolerance is the promotion margin. A champion that has lost less than the margin
# cannot be replaced by a challenger that merely recovers the loss: that challenger's advantage
# on the gate window is the loss, below the margin, and the gate refuses it. A retrain on a
# smaller drop is work the gate discards by construction, so the trigger starts where the gate
# can act. reports/monitoring/decay.json records the largest drop an in-control weekly batch
# showed against the reference, which is the number this has to sit above.
DECAY_TOLERANCE = PROMOTION_MARGIN

# "Sustained" is the smallest run that is not a spike: the drift flag raised on this many
# consecutive cycles. reports/monitoring/drift.json records the leave-one-out false alert rate
# per cycle; two in a row is that rate squared if cycles were independent, and the artifact
# records the longest run the in-control batches actually produced.
SUSTAINED_CYCLES = 2

# Days after a batch closes before its labels are read. An input, not a measurement: ADR 0032
# swept 15 to 90 and found nothing in this file that says where the true chargeback delay sits.
# A deployment replaces this with a measured delay; the demo's clock runs on it.
MATURITY_DAYS = 30

PRODUCTION_ALIAS = serving.MODEL_ALIAS
PREVIOUS_ALIAS = "previous"
CHALLENGER_ALIAS = "challenger"
ROLLED_BACK_ALIAS = "rolled-back"

FAMILY = "xgboost"
IMBALANCE = "none"


class LifecycleError(RuntimeError):
    """A lifecycle step asked for something the state cannot give: a rollback with no previous."""


# --- the retrain decision ---------------------------------------------------------------------------


def decay_flag(report: Mapping[str, Any], tolerance: float = DECAY_TOLERANCE) -> bool:
    """Whether one decay report is a decay: the drop clears the tolerance and its interval
    excludes zero. A drop inside the interval is noise; a drop outside it but under the
    tolerance is real and too small to act on."""
    drop = report["drop"]
    return bool(float(drop["point"]) >= tolerance and bool(drop["excludes_zero"]))


def should_retrain(
    cycles: Sequence[Mapping[str, Any]],
    sustained_cycles: int = SUSTAINED_CYCLES,
) -> dict[str, Any]:
    """Read the cycle history, oldest first, and say whether to train a challenger and why.

    Each cycle carries `drift_alert` (the drift job's batch flag, or None when no batch closed
    that cycle) and `decay` (the decay job's flag on the batch that matured that cycle, or None
    when none did). Decay on the most recent evaluated batch wins; failing that, the drift flag
    on the last `sustained_cycles` cycles in a row; failing that, nothing.
    """
    if sustained_cycles < 2:
        raise ValueError("sustained means more than one cycle")
    evaluated = [c for c in cycles if c.get("decay") is not None]
    latest = evaluated[-1] if evaluated else None
    run = 0
    for cycle in reversed(cycles):
        if cycle.get("drift_alert") is True:
            run += 1
        else:
            break
    out: dict[str, Any] = {
        "retrain": False,
        "reason": None,
        "latest_decay_cycle": latest["cycle"] if latest else None,
        "latest_decay": bool(latest["decay"]) if latest else None,
        "consecutive_drift_alerts": run,
        "sustained_cycles": sustained_cycles,
    }
    if latest is not None and latest["decay"]:
        out.update(retrain=True, reason="decay")
    elif run >= sustained_cycles:
        out.update(retrain=True, reason="sustained_drift")
    return out


# --- the windows ------------------------------------------------------------------------------------


@dataclass(frozen=True)
class ChallengerWindows:
    """Days of mature data a challenger takes, newest first: the gate window the fit never
    sees, the calibration window the threshold and calibrator are read off, the fit window."""

    fit_days: int
    calibration_days: int
    gate_days: int

    def __post_init__(self) -> None:
        for name in ("fit_days", "calibration_days", "gate_days"):
            if getattr(self, name) < 1:
                raise ValueError(f"{name} must be at least one day")


def challenger_bounds(mature_end_dt: int, windows: ChallengerWindows) -> dict[str, int]:
    """Cut the mature data ending at `mature_end_dt` into the three windows, newest first.

    Every bound is `[start, end)` on the clock. The gate window is the most recent mature data
    because it is the closest thing to the traffic the promoted model will see; the fit window
    is the oldest so that nothing it learned from is scored at the gate.
    """
    day = config.SECONDS_PER_DAY
    gate_end = int(mature_end_dt)
    gate_start = gate_end - windows.gate_days * day
    calibration_start = gate_start - windows.calibration_days * day
    fit_start = calibration_start - windows.fit_days * day
    return {
        "fit_start_dt": fit_start,
        "fit_end_dt": calibration_start,
        "calibration_start_dt": calibration_start,
        "calibration_end_dt": gate_start,
        "gate_start_dt": gate_start,
        "gate_end_dt": gate_end,
    }


def _window(frame: pd.DataFrame, start_dt: int, end_dt: int) -> pd.DataFrame:
    dt = frame[config.TIME_COLUMN]
    return frame.loc[(dt >= start_dt) & (dt < end_dt)]


# --- the challenger -----------------------------------------------------------------------------------


@dataclass
class Challenger:
    """A fitted challenger with everything its serving bundle needs, before it is written."""

    model: Any
    fitted: dict[str, Any]
    plan: dict[str, Any]
    serving: dict[str, Any]
    bounds: dict[str, int]
    fit: dict[str, Any]

    def scores(self, frame: pd.DataFrame) -> npt.NDArray[np.float64]:
        """The batch path: prepare, take the stack, score. What `serving` does one row at a time."""
        prepared = prepare.apply_preparation(frame, self.fitted, self.plan)
        x = modelling.tree_matrix(prepared, self.serving["columns"]).to_numpy(dtype="float32")
        return modelling.score(self.model, x)


def _without(declared: Mapping[str, Any], dropped: Sequence[str]) -> dict[str, Any]:
    """The stage 3 contract less the columns this fit did not produce, so the served row is
    validated against what the bundle's pipeline makes rather than what the champion's did."""
    out = dict(declared)
    out["columns"] = [spec for spec in declared["columns"] if spec["column"] not in set(dropped)]
    out["n_columns"] = len(out["columns"])
    return out


def raw_columns(frame: pd.DataFrame) -> list[str]:
    """The columns a payload may carry: the joined file's, less the two derived at load."""
    derived = (config.ENTITY_ID_COLUMN, config.CARD_START_DAY_COLUMN)
    return [str(c) for c in frame.columns if c not in derived]


def calibrator_breakpoints(
    score: npt.NDArray[np.float64], y: npt.NDArray[np.int_], fitted_on: str
) -> dict[str, Any]:
    """The isotonic fit as breakpoints, the form the serving bundle stores (stage 8)."""
    calibrator = evaluation.fit_calibrator(score, y)
    x = np.asarray(calibrator.X_thresholds_, dtype="float64")
    yy = np.asarray(calibrator.y_thresholds_, dtype="float64")
    return {
        "x": x.tolist(),
        "y": yy.tolist(),
        "n_breakpoints": int(x.size),
        "fitted_on": fitted_on,
        "method": "sklearn IsotonicRegression(y_min=0, y_max=1, out_of_bounds='clip'), stored "
        "as its breakpoints and applied with np.interp",
    }


def fit_challenger(
    frame: pd.DataFrame,
    bounds: Mapping[str, int],
    columns: Sequence[str],
    hyperparameters: Mapping[str, Any],
    schema_report: Mapping[str, Any],
    plan: Mapping[str, Any] | None = None,
    facts: cleaning.EdaFacts | None = None,
    decisions: Mapping[str, Any] | None = None,
    seed: int = config.SEED,
) -> Challenger:
    """Fit a challenger on `bounds` through the identical pipeline: stage 3 on the fit window
    under the guard at the fit window's end, the stage 6 family and hyperparameters on the
    stage 6 stack, the calibrator and threshold on the calibration window.

    `frame` is the joined raw file with the entity key attached. The column plan, the stage 2
    facts and the stage 3 decisions are the committed ones unless a caller supplies them: they
    are decisions about the pipeline, not state fitted on a window, and a challenger that
    re-decided them would be a different pipeline.
    """
    plan = dict(plan) if plan is not None else prepare.read_column_plan()
    facts = facts if facts is not None else cleaning.EdaFacts.load()
    decisions = dict(decisions) if decisions is not None else prepare.read_decisions()

    fit_rows = _window(frame, bounds["fit_start_dt"], bounds["fit_end_dt"])
    calibration_rows = _window(frame, bounds["calibration_start_dt"], bounds["calibration_end_dt"])
    if len(fit_rows) == 0 or len(calibration_rows) == 0:
        raise LifecycleError("a challenger window holds no rows")

    started = time.perf_counter()
    with data_loader.training_boundary(int(bounds["fit_end_dt"])):
        fitted = prepare.fit_preparation(
            fit_rows,
            plan,
            facts,
            d_origin_columns=decisions["d_origin_columns"],
            v_strategy=decisions["v_strategy"],
            lag_days=int(decisions["lag_days"]),
            smoothing=float(decisions["smoothing"]),
            seed=seed,
        )
        buckets = features.fit_dist_buckets(encoders.add_normalised_free_text(fit_rows))
    prepared = prepare.apply_preparation(fit_rows, fitted, plan)
    # The pipeline's rules can leave a column out on a different window: the frequency encoder
    # skips a column under its cardinality floor, and addr2 has 67 levels over the training
    # split and about 29 over sixty days of it. The stack is the champion's less what the
    # window's fit did not produce, and the record says which.
    dropped = [c for c in columns if c not in prepared.columns]
    columns = [c for c in columns if c in prepared.columns]
    if not columns:
        raise LifecycleError("the challenger's pipeline produced none of the stack's columns")
    x = modelling.tree_matrix(prepared, columns).to_numpy(dtype="float32")
    y = fit_rows[config.TARGET].to_numpy(dtype="int64")
    model = modelling.make_model(FAMILY, IMBALANCE, y, seed, hyperparameters)
    model.fit(x, y)
    fit_seconds = time.perf_counter() - started

    challenger = Challenger(
        model=model,
        fitted=fitted,
        plan=plan,
        serving={"columns": list(columns)},
        bounds=dict(bounds),
        fit={},
    )
    s_cal = challenger.scores(calibration_rows)
    y_cal = calibration_rows[config.TARGET].to_numpy(dtype="int64")
    n_days = (
        bounds["calibration_end_dt"] - bounds["calibration_start_dt"]
    ) / config.SECONDS_PER_DAY
    calibrator = calibrator_breakpoints(s_cal, y_cal, "calibration window")
    vertex = evaluation.best_f1_vertex(y_cal, s_cal, n_days)
    bands = evaluation.cost_bands()
    challenger.serving = {
        "model_name": serving.MODEL_NAME,
        "alias": CHALLENGER_ALIAS,
        "family": FAMILY,
        "stack": {
            "name": "challenger, the champion's stack less what the window did not produce",
            "columns_from": "champion",
            "columns_dropped": dropped,
        },
        "hyperparameters": dict(hyperparameters),
        "columns": list(columns),
        "n_columns": len(columns),
        "raw_columns": raw_columns(frame),
        "dist_buckets": buckets,
        "decisions": decisions,
        "calibrator": calibrator,
        "bands": {
            "low": bands["low"],
            "high": bands["high"],
            "on": "calibrated probability",
            "costs": bands["costs"],
            "source": "evaluation.cost_bands() from config, as reports/operating_points.json",
        },
        "tuned_threshold": {
            "threshold": vertex["threshold"],
            "on": "raw score",
            "rule": "largest F1 on the calibration window",
            "source": "lifecycle.fit_challenger, calibration window",
        },
        "schema": _without(schema_report["schema"], dropped),
        "inference_threads": serving.INFERENCE_THREADS,
        "windows": dict(bounds),
        "train_only_boundary_dt": int(bounds["fit_end_dt"]),
    }
    challenger.fit = {
        "n_columns": len(columns),
        "columns_dropped": dropped,
        "n_fit_rows": int(y.size),
        "n_fit_fraud": int(y.sum()),
        "fit_fraud_rate": float(y.mean()),
        "n_calibration_rows": int(y_cal.size),
        "n_calibration_fraud": int(y_cal.sum()),
        "calibration_pr_auc": float(evaluation.pr_auc(y_cal, s_cal)),
        "tuned_threshold": float(vertex["threshold"]),
        "calibrator_breakpoints": calibrator["n_breakpoints"],
        "fit_seconds": fit_seconds,
        "seed": seed,
    }
    return challenger


# --- the gate ------------------------------------------------------------------------------------------


def gate(
    y: npt.NDArray[np.int_],
    champion: npt.NDArray[np.float64],
    challenger: npt.NDArray[np.float64],
    groups: npt.NDArray[Any] | None,
    n_boot: int,
    seed: int,
    margin: float = PROMOTION_MARGIN,
) -> dict[str, Any]:
    """Promote only when the challenger beats the champion by the margin, above the noise.

    Both models are scored on the same held-out rows and bootstrapped on identical resamples
    (by card when `groups` is given, which is the resample the margin came from), so the
    difference is paired. Two conditions, both required: the point difference is at least the
    margin, and the paired interval on the difference lies above zero. The first refuses a
    challenger that is better but not usefully so; the second refuses one whose advantage this
    window cannot distinguish from resampling.
    """
    summary = evaluation.paired_bootstrap(
        np.asarray(y, dtype="int64"),
        {"challenger": challenger, "champion": champion},
        n_boot,
        seed,
        groups=groups,
    )
    pair = summary["pairs"][0]
    difference = pair["difference"]
    clears_margin = bool(difference["point"] >= margin)
    above_noise = bool(difference["low"] > 0.0)
    if clears_margin and above_noise:
        reason = "promoted: the advantage clears the margin and its interval lies above zero"
    elif not clears_margin and difference["point"] > 0:
        reason = "refused: better, but by less than the margin"
    elif not clears_margin:
        reason = "refused: not better"
    else:
        reason = "refused: clears the margin on the point but the interval reaches zero"
    return {
        "promote": bool(clears_margin and above_noise),
        "reason": reason,
        "margin": margin,
        "clears_margin": clears_margin,
        "above_noise": above_noise,
        "metric": summary["metric"],
        "resample": summary["resample"],
        "n_rows": summary["n_rows"],
        "n_groups": summary["n_groups"],
        "n_boot": summary["n_boot"],
        "n_valid": summary["n_valid"],
        "seed": summary["seed"],
        "champion": summary["per_model"]["champion"],
        "challenger": summary["per_model"]["challenger"],
        "difference": difference,
        "sign_agreement": pair["sign_agreement"],
    }


# --- the registry -------------------------------------------------------------------------------------


class Registry:
    """Alias moves on the stage 8 registry: promote, roll back, and say what points where."""

    def __init__(
        self,
        tracking_uri: str,
        artifact_root: Path,
        name: str = serving.MODEL_NAME,
        experiment: str = serving.EXPERIMENT,
    ) -> None:
        self.tracking_uri = tracking_uri
        self.artifact_root = artifact_root
        self.name = name
        self.experiment = experiment

    def _client(self) -> Any:
        import mlflow
        from mlflow import MlflowClient

        mlflow.set_tracking_uri(self.tracking_uri)
        return MlflowClient()

    def version_for(self, alias: str) -> int | None:
        from mlflow.exceptions import MlflowException

        try:
            return int(self._client().get_model_version_by_alias(self.name, alias).version)
        except MlflowException:
            return None

    def aliases(self) -> dict[str, int | None]:
        return {
            alias: self.version_for(alias)
            for alias in (PRODUCTION_ALIAS, PREVIOUS_ALIAS, CHALLENGER_ALIAS, ROLLED_BACK_ALIAS)
        }

    def register(
        self, paths: Mapping[str, Path], params: Mapping[str, Any], alias: str
    ) -> dict[str, Any]:
        return serving.register_bundle(
            paths,
            params,
            self.tracking_uri,
            self.artifact_root,
            name=self.name,
            alias=alias,
            experiment=self.experiment,
        )

    def promote(self, version: int) -> dict[str, Any]:
        """Point production at `version`, keeping the version it pointed at as `previous`."""
        client = self._client()
        current = self.version_for(PRODUCTION_ALIAS)
        if current == version:
            raise LifecycleError(f"version {version} is already {PRODUCTION_ALIAS}")
        if current is not None:
            client.set_registered_model_alias(self.name, PREVIOUS_ALIAS, str(current))
        client.set_registered_model_alias(self.name, PRODUCTION_ALIAS, str(version))
        with contextlib.suppress(Exception):
            client.delete_registered_model_alias(self.name, CHALLENGER_ALIAS)
        return {"action": "promote", "production": version, "previous": current}

    def rollback(self) -> dict[str, Any]:
        """Point production back at `previous`; the version rolled back from is marked."""
        client = self._client()
        previous = self.version_for(PREVIOUS_ALIAS)
        if previous is None:
            raise LifecycleError(f"nothing to roll back to: no {PREVIOUS_ALIAS} alias")
        current = self.version_for(PRODUCTION_ALIAS)
        client.set_registered_model_alias(self.name, PRODUCTION_ALIAS, str(previous))
        client.delete_registered_model_alias(self.name, PREVIOUS_ALIAS)
        if current is not None:
            client.set_registered_model_alias(self.name, ROLLED_BACK_ALIAS, str(current))
        return {"action": "rollback", "production": previous, "rolled_back": current}
