"""Build the lifecycle demo page from the committed stage 9 artifacts. Writes docs/demo/index.html.

Usage:
    make demo-page
    .venv/bin/python scripts/demo_page.py

The page is one self-contained HTML file for a static host: every number it shows is read from
an artifact under reports/ at build time and inlined as JSON, and the page's own script renders
it. It reads no data and fits no model, so a copy of the file is the whole deployment. The
committed page is regenerated by this script alone and a test compares the two byte for byte,
so the page can never quote a number the artifacts do not hold.

What the page replays, all from reports/lifecycle_demo.json: the fourteen weekly cycles of the
seed-pinned run, the drift job at each batch close, the decay job as each batch's labels mature,
the retrain decision, the four challengers at the gate, the two promotions and the rollback
drill. The headline tiles read reports/metric_variance.json, reports/operating_points.json,
reports/latency.json, reports/parity.json and reports/split_summary.json; the inputs card reads
reports/monitoring/drift.json and reports/monitoring/decay.json; the drift character card reads
reports/adversarial_validation.json.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

OUT_DEFAULT = Path("docs/demo/index.html")

# The keys the page reads from each cycle's challenger record. The fit block is trimmed to what
# the console shows; the gate block is kept whole because the gate visual draws every field.
CHALLENGER_KEYS = (
    "trained",
    "reason",
    "number",
    "trigger",
    "windows",
    "drifted_rows_in_fit_window",
    "gate_rows",
    "gate_fraud",
    "gate_drifted_rows",
    "gate",
    "registry",
    "promotion",
    "mature_end_day",
    "gate_start_day",
    "champion_train_end_day",
)
FIT_KEYS = (
    "n_columns",
    "columns_dropped",
    "n_fit_rows",
    "n_fit_fraud",
    "n_calibration_rows",
    "calibration_pr_auc",
    "tuned_threshold",
    "fit_seconds",
)
DECAY_KEYS = (
    "batch",
    "end_day",
    "matured_at_day",
    "drifted_rows",
    "n_rows",
    "n_fraud",
    "pr_auc",
    "pr_auc_low",
    "pr_auc_high",
    "precision",
    "recall",
    "reference_pr_auc",
    "drop",
    "drop_low",
    "drop_excludes_zero",
    "decay",
)


def load(path: Path) -> dict[str, Any]:
    return dict(json.loads(path.read_text(encoding="utf-8")))


def pick(record: dict[str, Any], keys: tuple[str, ...]) -> dict[str, Any]:
    return {k: record[k] for k in keys if k in record}


def provenance(artifact: dict[str, Any], path: str) -> dict[str, Any]:
    return {
        "artifact": path,
        "regenerate_with": artifact.get("regenerate_with"),
        "git_commit": artifact.get("git_commit"),
        "generated_at_utc": artifact.get("generated_at_utc"),
    }


def compact_cycle(cycle: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {
        "cycle": cycle["cycle"],
        "as_of_day": cycle["as_of_day"],
        "champion": cycle["champion"],
        "drift": cycle["drift"],
        "decay": [pick(d, DECAY_KEYS) for d in cycle["decay"]],
        "immature": cycle["immature"],
        "decision": cycle["decision"],
    }
    challenger = cycle.get("challenger")
    if challenger is not None:
        record = pick(challenger, CHALLENGER_KEYS)
        if "fit" in challenger:
            record["fit"] = pick(challenger["fit"], FIT_KEYS)
        out["challenger"] = record
    return out


def extract(reports: Path) -> dict[str, Any]:
    """Every number the page shows, read once from the artifacts and shaped for the renderer."""
    lifecycle = load(reports / "lifecycle_demo.json")
    drift = load(reports / "monitoring" / "drift.json")
    decay = load(reports / "monitoring" / "decay.json")
    adversarial = load(reports / "adversarial_validation.json")
    variance = load(reports / "metric_variance.json")
    operating = load(reports / "operating_points.json")
    latency = load(reports / "latency.json")
    parity = load(reports / "parity.json")
    split = load(reports / "split_summary.json")

    shipped = variance["by_row"]["per_model"]["shipped"]
    xgb_p50 = latency["summary"]["pinned_p50_by_family"]["xgboost"]
    xgb_p99 = latency["summary"]["pinned_p99_by_family"]["xgboost"]
    memory = parity["backends"]["memory"]
    calibration = drift["calibration"]
    in_control_drift = drift["in_control"]
    in_control_decay = decay["in_control"]
    fits = adversarial["fits"]

    def fit_summary(name: str) -> dict[str, Any]:
        fit = fits[name]
        return {
            "n_columns": fit["n_columns"],
            "auc_out_of_fold": fit["auc"]["out_of_fold"],
            "entity_and_clock_share_of_top_10_gain": fit["entity_and_clock_share_of_top_10_gain"],
            "top": [
                pick(row, ("rank", "column", "group", "gain_share")) for row in fit["top"][:10]
            ],
        }

    return {
        "run": {
            "generated_at_utc": lifecycle["generated_at_utc"],
            "git_commit": lifecycle["git_commit"],
            "seed": lifecycle["seed"],
            "seconds": lifecycle["seconds"],
            "regenerate_with": lifecycle["regenerate_with"],
            "environment": lifecycle["environment"],
        },
        "headline": {
            "pr_auc": {
                "point": shipped["point"],
                "low": shipped["low"],
                "high": shipped["high"],
                "half_width": shipped["half_width"],
                "n_boot": variance["by_row"]["n_boot"],
                "resample": variance["by_row"]["resample"],
            },
            "roc_auc_test": operating["primary_metric"]["test"]["roc_auc"],
            "n_rows": split["totals"]["n_rows"],
            "n_train_rows": split["splits"]["train"]["n_rows"],
            "n_test_rows": split["splits"]["test"]["n_rows"],
            "fraud_rate": split["totals"]["fraud_rate"],
            "n_columns": latency["models"]["n_columns"],
            "latency": {
                "p50_ms_median": xgb_p50["median"],
                "p99_ms_median": xgb_p99["median"],
                "n_repeats": latency["summary"]["n_repeats"],
                "n_rows": latency["method"]["rows"]["n"],
                "inference_threads": latency["pinning"]["inference_threads"],
            },
            "parity": {
                "n_rows": parity["stream"]["n_rows"],
                "n_days": parity["stream"]["n_days"],
                "n_features": memory["n_features"],
                "max_abs_difference": memory["max_abs_difference_over_all_features"],
                "bit_identical": memory["bit_identical"],
            },
        },
        "inputs": lifecycle["inputs"],
        "stream": lifecycle["stream"],
        "champion": lifecycle["champion"],
        "noise_band": {
            "by_card": variance["by_card"]["widest_paired_half_width"],
            "by_row": variance["by_row"]["widest_paired_half_width"],
            "n_boot": variance["n_boot"],
        },
        "drift_job": {
            "n_columns": calibration["n_columns"],
            "n_alertable_columns": calibration["n_alertable_columns"],
            "n_batches": calibration["n_batches"],
            "batch_days": calibration["batch_days"],
            "feature_count_edge": calibration["feature_count_edge"],
            "score_alert_edge": calibration["score_alert_edge"],
            "worst_batch_score_psi": calibration["worst_batch_score_psi"],
            "textbook_alert_band_per_batch": in_control_drift["textbook_alert_band_per_batch"],
            "calibrated_alerts_per_batch": in_control_drift["calibrated_alerts_per_batch"],
            "score_psi_per_batch": in_control_drift["score_psi_per_batch"],
            "longest_run_of_drift_alerts": in_control_drift["longest_run_of_drift_alerts"],
            "leave_one_out_rate_any_alert": in_control_drift["leave_one_out"]["rate_any_alert"],
            "stage_2_psi_test_above_0_10": drift["against_stage_2"]["stage_2_summary"][
                "n_psi_test_above_0_10"
            ],
        },
        "decay_job": {
            "maturity_days": decay["maturity_days"],
            "reference": {
                "window": decay["reference"]["window"],
                "pr_auc": decay["reference"]["pr_auc"],
                "n_rows": decay["reference"]["n_rows"],
                "n_fraud": decay["reference"]["n_fraud"],
                "threshold": decay["reference"]["threshold"],
            },
            "n_batches": in_control_decay["n_batches"],
            "pr_auc_per_batch": in_control_decay["pr_auc_per_batch"],
            "drop_per_batch": in_control_decay["drop_per_batch"],
            "largest_drop": in_control_decay["largest_drop"],
            "n_decay": in_control_decay["n_decay"],
            "decay_tolerance": in_control_decay["decay_tolerance"],
            "headroom": in_control_decay["headroom"],
        },
        "adversarial": {
            "n_train_rows": adversarial["n_train_rows"],
            "n_test_rows": adversarial["n_test_rows"],
            "fits": {name: fit_summary(name) for name in fits},
            "spearman_gain_vs_stage_2_psi": adversarial["against_stage_2"][
                "spearman_gain_vs_stage_2_psi"
            ]["rho"],
        },
        "cycles": [compact_cycle(c) for c in lifecycle["cycles"]],
        "promotion": {
            "cycle": lifecycle["promotion"]["cycle"],
            "version": lifecycle["promotion"]["version"],
            "previous_version": lifecycle["promotion"]["previous_version"],
            "new_reference_pr_auc": lifecycle["promotion"]["new_reference_pr_auc"],
            "new_drift_reference": lifecycle["promotion"]["new_drift_reference"],
        },
        "rollback": lifecycle["rollback"],
        "sources": [
            provenance(lifecycle, "reports/lifecycle_demo.json"),
            provenance(drift, "reports/monitoring/drift.json"),
            provenance(decay, "reports/monitoring/decay.json"),
            provenance(adversarial, "reports/adversarial_validation.json"),
            provenance(variance, "reports/metric_variance.json"),
            provenance(operating, "reports/operating_points.json"),
            provenance(latency, "reports/latency.json"),
            provenance(parity, "reports/parity.json"),
            provenance(split, "reports/split_summary.json"),
        ],
    }


def render(data: dict[str, Any]) -> str:
    payload = json.dumps(data, sort_keys=True, separators=(",", ":")).replace("</", "<\\/")
    return TEMPLATE.replace("__DATA__", payload)


TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Two Clocks and a Gate</title>
<meta name="description" content="A recorded replay of a fraud model's monitoring and retraining loop: a drift job, a decay job, a promotion gate and a rollback, every number from one seed-pinned run.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
:root {
  color-scheme: light;
  --ground: #f3f5f8;
  --surface: #ffffff;
  --surface-2: #e9edf2;
  --ink: #161b22;
  --ink-2: #4f5b68;
  --ink-3: #7c8794;
  --line: #dbe1e8;
  --line-2: #b9c2cc;
  --blue: #2a78d6;
  --blue-soft: rgba(42, 120, 214, 0.14);
  --crit: #c93a3a;
  --crit-soft: rgba(208, 59, 59, 0.13);
  --good: #0f7f16;
  --good-soft: rgba(12, 163, 12, 0.14);
  --warn: #9a6a08;
  --warn-soft: rgba(250, 178, 25, 0.22);
  --sans: "IBM Plex Sans", system-ui, -apple-system, "Segoe UI", sans-serif;
  --mono: "IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
    --ground: #0e1116;
    --surface: #161b22;
    --surface-2: #1f262f;
    --ink: #e8ecf1;
    --ink-2: #a5aeb9;
    --ink-3: #7d8792;
    --line: #2a323c;
    --line-2: #3b4550;
    --blue: #4a90e8;
    --blue-soft: rgba(74, 144, 232, 0.2);
    --crit: #e46464;
    --crit-soft: rgba(228, 100, 100, 0.18);
    --good: #3fb54a;
    --good-soft: rgba(63, 181, 74, 0.18);
    --warn: #e0a72c;
    --warn-soft: rgba(224, 167, 44, 0.2);
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
  --ground: #0e1116;
  --surface: #161b22;
  --surface-2: #1f262f;
  --ink: #e8ecf1;
  --ink-2: #a5aeb9;
  --ink-3: #7d8792;
  --line: #2a323c;
  --line-2: #3b4550;
  --blue: #4a90e8;
  --blue-soft: rgba(74, 144, 232, 0.2);
  --crit: #e46464;
  --crit-soft: rgba(228, 100, 100, 0.18);
  --good: #3fb54a;
  --good-soft: rgba(63, 181, 74, 0.18);
  --warn: #e0a72c;
  --warn-soft: rgba(224, 167, 44, 0.2);
}
* { box-sizing: border-box; }
html, body { margin: 0; }
body {
  background: var(--ground);
  color: var(--ink);
  font-family: var(--sans);
  font-size: 15px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--blue); }
code, .mono { font-family: var(--mono); font-size: 0.92em; }
.wrap { max-width: 1140px; margin: 0 auto; padding: 40px 24px 64px; }
.eyebrow {
  font-family: var(--mono);
  font-size: 12px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--ink-3);
  margin: 0 0 12px;
}
h1 {
  font-size: clamp(30px, 4.2vw, 44px);
  font-weight: 600;
  line-height: 1.08;
  letter-spacing: -0.015em;
  margin: 0 0 16px;
  text-wrap: balance;
}
h2 {
  font-size: 20px;
  font-weight: 600;
  letter-spacing: -0.01em;
  margin: 0 0 6px;
  text-wrap: balance;
}
h3 {
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--ink-2);
  margin: 0 0 10px;
}
p { margin: 0 0 12px; }
.lede { font-size: 17px; color: var(--ink-2); max-width: 66ch; }
.lede strong { color: var(--ink); font-weight: 500; }
section { margin-top: 48px; }
.section-head { display: flex; flex-direction: column; gap: 2px; margin-bottom: 18px; }
.section-head p { color: var(--ink-2); max-width: 70ch; margin: 0; }

.tiles { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin-top: 28px; }
.tile {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 16px 18px 14px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.tile .label { font-size: 12.5px; color: var(--ink-2); line-height: 1.35; }
.tile .value { font-size: 30px; font-weight: 600; letter-spacing: -0.02em; line-height: 1.1; margin-top: 4px; }
.tile .value small { font-size: 15px; font-weight: 500; color: var(--ink-2); margin-left: 2px; }
.tile .note { font-size: 12px; color: var(--ink-3); line-height: 1.4; margin-top: 2px; }

.clock {
  position: sticky;
  top: 0;
  z-index: 5;
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 12px 14px;
  display: flex;
  align-items: center;
  gap: 14px;
  flex-wrap: wrap;
}
.controls { display: flex; gap: 6px; align-items: center; }
button {
  font-family: inherit;
  font-size: 13.5px;
  font-weight: 500;
  color: var(--ink);
  background: var(--surface-2);
  border: 1px solid var(--line);
  border-radius: 4px;
  padding: 6px 12px;
  cursor: pointer;
  line-height: 1.2;
}
button:hover { border-color: var(--line-2); }
button:focus-visible, .step:focus-visible, .mark:focus-visible { outline: 2px solid var(--blue); outline-offset: 2px; }
button.primary { background: var(--blue); border-color: var(--blue); color: #fff; min-width: 74px; }
.readout { font-family: var(--mono); font-size: 13px; color: var(--ink-2); white-space: nowrap; }
.readout b { color: var(--ink); font-weight: 500; }
.steps { display: flex; gap: 3px; flex: 1 1 380px; min-width: 0; }
.step {
  flex: 1 1 0;
  min-width: 0;
  border: 1px solid var(--line);
  border-radius: 4px;
  background: var(--ground);
  padding: 5px 0 4px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 3px;
  cursor: pointer;
  font-family: var(--mono);
  font-size: 11.5px;
  color: var(--ink-2);
  line-height: 1;
}
.step:hover { border-color: var(--line-2); }
.step.on { background: var(--blue); border-color: var(--blue); color: #fff; }
.step .glyphs { display: flex; gap: 2px; height: 6px; }
.step .g { width: 6px; height: 6px; border-radius: 50%; }
.g.flag { background: var(--crit); }
.g.decay { background: var(--crit); border-radius: 1px; }
.g.gate { background: var(--ink-3); border-radius: 1px; width: 8px; }
.g.up { background: var(--good); border-radius: 1px; width: 8px; }
.g.none { background: transparent; }
.step.on .g.flag, .step.on .g.decay { background: #fff; }
.step.on .g.gate { background: rgba(255,255,255,0.7); }
.step.on .g.up { background: #fff; }

.replay { display: grid; grid-template-columns: minmax(0, 3fr) minmax(0, 2fr); gap: 18px; margin-top: 18px; align-items: start; }
.panel { background: var(--surface); border: 1px solid var(--line); border-radius: 6px; padding: 16px 18px; }
.chart-wrap { position: relative; }
.chart-wrap svg { width: 100%; height: auto; display: block; font-family: var(--sans); }
.chart-title { font-size: 13px; font-weight: 500; color: var(--ink-2); margin: 0 0 6px; }
.legend { display: flex; flex-wrap: wrap; gap: 6px 16px; font-size: 12px; color: var(--ink-2); margin: 8px 0 0; padding: 0; list-style: none; }
.legend li { display: flex; align-items: center; gap: 6px; }
.key { display: inline-block; width: 14px; height: 0; border-top: 2px solid var(--blue); }
.key.dot { width: 9px; height: 9px; border: 0; border-radius: 50%; background: var(--blue); }
.key.dot.crit { background: var(--crit); }
.key.ref { border-top: 1.5px solid var(--ink-3); }
.key.tol { border-top: 1.5px solid var(--crit); }
.key.edge { border-top: 1.5px solid var(--crit); }
.key.tri { width: 0; height: 0; border-left: 5px solid transparent; border-right: 5px solid transparent; border-top: 0; border-bottom: 9px solid var(--good); }
.key.tri.down { border-bottom: 0; border-top: 9px solid var(--ink-3); }
.key.hollow { width: 8px; height: 8px; border: 1.5px solid var(--ink-3); border-radius: 50%; background: transparent; }
.tip {
  position: absolute;
  pointer-events: none;
  background: var(--ink);
  color: var(--ground);
  font-family: var(--mono);
  font-size: 11.5px;
  line-height: 1.45;
  padding: 6px 9px;
  border-radius: 4px;
  max-width: 260px;
  white-space: pre-line;
  transform: translate(-50%, calc(-100% - 10px));
  opacity: 0;
  transition: opacity 120ms;
}
.tip.show { opacity: 1; }
svg text { fill: var(--ink-2); font-size: 11px; }
svg text.mono { font-family: var(--mono); fill: var(--ink-3); }
svg text.lab { font-size: 11px; fill: var(--ink-2); }
svg .grid { stroke: var(--line); stroke-width: 1; }
svg .axis { stroke: var(--line-2); stroke-width: 1; }
svg .future { opacity: 0.16; }
svg .mark { cursor: pointer; }
svg .cursor { stroke: var(--ink); stroke-width: 1; stroke-dasharray: 2 3; }
@media (prefers-reduced-motion: no-preference) {
  svg .rev { transition: opacity 220ms ease; }
}

.console { display: flex; flex-direction: column; gap: 12px; }
.card { background: var(--surface); border: 1px solid var(--line); border-radius: 6px; padding: 14px 16px; }
.card .head { display: flex; justify-content: space-between; align-items: baseline; gap: 10px; margin-bottom: 8px; }
.card .head h3 { margin: 0; }
.pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 500;
  padding: 2px 9px;
  border-radius: 999px;
  background: var(--surface-2);
  color: var(--ink-2);
  white-space: nowrap;
}
.pill::before { content: ""; width: 7px; height: 7px; border-radius: 50%; background: var(--ink-3); }
.pill.crit { background: var(--crit-soft); color: var(--crit); }
.pill.crit::before { background: var(--crit); }
.pill.good { background: var(--good-soft); color: var(--good); }
.pill.good::before { background: var(--good); }
.pill.warn { background: var(--warn-soft); color: var(--warn); }
.pill.warn::before { background: var(--warn); }
.pill.blue { background: var(--blue-soft); color: var(--blue); }
.pill.blue::before { background: var(--blue); }
.kv { display: grid; grid-template-columns: max-content 1fr; gap: 4px 14px; font-size: 13.5px; margin: 0; }
.kv dt { color: var(--ink-2); margin: 0; }
.kv dd { margin: 0; font-family: var(--mono); font-size: 13px; font-variant-numeric: tabular-nums; }
.kv dd.text { font-family: var(--sans); font-size: 13.5px; }
.muted { color: var(--ink-3); }
.quiet { color: var(--ink-3); font-size: 13px; margin: 0; }
.bars { display: grid; grid-template-columns: max-content 1fr max-content; gap: 4px 10px; align-items: center; font-family: var(--mono); font-size: 12px; margin-top: 10px; }
.bars .track { height: 8px; background: var(--surface-2); border-radius: 2px; overflow: hidden; }
.bars .fill { height: 100%; background: var(--blue); border-radius: 0 2px 2px 0; }
.bars .fill.crit { background: var(--crit); }
.bars .n { text-align: right; font-variant-numeric: tabular-nums; color: var(--ink-2); }
.gate-line { margin: 12px 0 4px; }
.gate-line svg { width: 100%; max-width: 340px; height: auto; display: block; overflow: visible; }
.verdict { font-size: 13.5px; margin-top: 6px; }
.chip-row { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }
.chip { font-family: var(--mono); font-size: 11.5px; padding: 1px 7px; border-radius: 3px; background: var(--surface-2); color: var(--ink-2); }
.chip.mature { background: var(--blue-soft); color: var(--blue); }
.chip.crit { background: var(--crit-soft); color: var(--crit); }

table { border-collapse: collapse; width: 100%; font-size: 13.5px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }
th { font-size: 12px; font-weight: 600; letter-spacing: 0.03em; text-transform: uppercase; color: var(--ink-2); }
td.num, th.num { text-align: right; font-family: var(--mono); font-size: 13px; font-variant-numeric: tabular-nums; white-space: nowrap; }
td.mono { font-family: var(--mono); font-size: 12.5px; }
.table-wrap { overflow-x: auto; }
.grid-2 { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }
.grid-3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }
.inputs .card p { font-size: 13.5px; color: var(--ink-2); margin: 0; }
.inputs .card p + p { margin-top: 6px; }
.inputs .card .big { font-family: var(--mono); font-size: 20px; color: var(--ink); font-weight: 500; margin: 0 0 4px; }
.arith { font-family: var(--mono); font-size: 12.5px; color: var(--ink-2); background: var(--ground); border-radius: 4px; padding: 8px 10px; margin: 8px 0 0; white-space: pre; overflow-x: auto; }
ul.plain { margin: 0; padding-left: 18px; }
ul.plain li { margin-bottom: 8px; color: var(--ink-2); max-width: 78ch; }
ul.plain li strong { color: var(--ink); font-weight: 500; }
footer { margin-top: 56px; padding-top: 18px; border-top: 1px solid var(--line); font-size: 12.5px; color: var(--ink-3); font-family: var(--mono); line-height: 1.6; }
@media (max-width: 900px) {
  .tiles { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .replay { grid-template-columns: 1fr; }
  .grid-3 { grid-template-columns: 1fr; }
  .grid-2 { grid-template-columns: 1fr; }
  .clock { position: static; }
}
@media (max-width: 560px) {
  .tiles { grid-template-columns: 1fr; }
  .wrap { padding: 28px 16px 48px; }
}
</style>
</head>
<body>
<script id="demo-data" type="application/json">__DATA__</script>
<div class="wrap">
<header>
  <p class="eyebrow">Fraud detection platform on IEEE-CIS, stage 9 of 10</p>
  <h1>Two clocks and a gate</h1>
  <p class="lede">A fraud model fails in two ways on two clocks. Its inputs can shift the day a batch closes, before a single label exists; its accuracy can only be measured once the chargebacks arrive, weeks later. This page replays one recorded run of the platform's lifecycle: <strong>a drift job that reads no labels, a decay job that waits for them, a retrain trigger that reads both, a challenger fitted through the same leakage-safe pipeline, a promotion gate with a margin derived from measured noise, and a rollback.</strong> Every number on the page is read from the committed artifact of one seed-pinned run.</p>
  <div class="tiles" id="tiles"></div>
</header>

<section id="run">
  <div class="section-head">
    <h2>The run, one cycle a week</h2>
    <p>Fourteen cycles over a stream of real consecutive weeks. From day 141 every raw row carries a change the model never saw. Step through, or press play. The charts reveal what each job had seen by that cycle; the console shows what each job wrote.</p>
  </div>
  <div class="clock">
    <div class="controls">
      <button class="primary" id="play" type="button">Play</button>
      <button id="prev" type="button" aria-label="previous cycle">&larr;</button>
      <button id="next" type="button" aria-label="next cycle">&rarr;</button>
    </div>
    <div class="readout" id="readout"></div>
    <div class="steps" id="steps" role="tablist" aria-label="cycles"></div>
  </div>
  <div class="replay">
    <div class="panel chart-wrap">
      <p class="chart-title" id="chart-title"></p>
      <div id="chart"></div>
      <div class="tip" id="tip"></div>
      <ul class="legend">
        <li><span class="key"></span> score PSI against the champion's training window</li>
        <li><span class="key edge"></span> score alert edge, shipped model</li>
        <li><span class="key dot"></span> matured batch, PR-AUC with its 95% interval</li>
        <li><span class="key dot crit"></span> decay: the drop clears the tolerance</li>
        <li><span class="key ref"></span> the champion's reference</li>
        <li><span class="key tol"></span> reference less the tolerance</li>
        <li><span class="key tri"></span> promoted</li>
        <li><span class="key tri down"></span> refused</li>
        <li><span class="key hollow"></span> retrain called, no challenger fitted</li>
      </ul>
    </div>
    <div class="console" id="console"></div>
  </div>
</section>

<section id="gate">
  <div class="section-head">
    <h2>The gate, four times</h2>
    <p>A challenger is promoted when its paired advantage on the gate window clears the margin and the interval lies above zero. Both refusals and both promotions are in the record, with the reason the gate wrote.</p>
  </div>
  <div class="panel table-wrap" id="ledger"></div>
</section>

<section id="inputs" class="inputs">
  <div class="section-head">
    <h2>Set before the run</h2>
    <p>The edges and margins are derived from measured quantities in earlier stages; the clocks and the injected shift are choices, labelled as such in the artifact.</p>
  </div>
  <div class="grid-3" id="inputs-grid"></div>
</section>

<section id="character">
  <div class="section-head">
    <h2>What kind of drift this file has on its own</h2>
    <p>Before the injection, one classifier was told to separate the training window from the test window on the shipped model's input columns. Which columns it leans on says what kind of shift the file carries.</p>
  </div>
  <div class="grid-2" id="character-grid"></div>
</section>

<section id="not">
  <div class="section-head">
    <h2>What this run does not establish</h2>
  </div>
  <div class="panel"><ul class="plain" id="not-list"></ul></div>
</section>

<section id="sources">
  <div class="section-head">
    <h2>Where every number comes from</h2>
    <p>Each artifact is committed with the command that regenerates it. The page is built from them by one script and a test compares the committed page with a fresh build.</p>
  </div>
  <div class="panel table-wrap" id="sources-table"></div>
</section>

<footer id="foot"></footer>
</div>

<script>
(function () {
  "use strict";
  var D = JSON.parse(document.getElementById("demo-data").textContent);
  var cycles = D.cycles;
  var N = cycles.length;
  var DRILL = N;
  var MARGIN = D.inputs.promotion_margin;
  var TOL = D.inputs.decay_tolerance;
  var REF0 = D.champion.accepted.pr_auc;
  var EDGE0 = D.champion.drift_reference.score_alert_edge;
  var INJECT = D.inputs.drift_from_day;

  function f4(x) { return x.toFixed(4); }
  function f2(x) { return x.toFixed(2); }
  function f3(x) { return x.toFixed(3); }
  function sg(x) { return (x >= 0 ? "+" : "-") + Math.abs(x).toFixed(4); }
  function int(x) { return x.toLocaleString("en-US"); }
  function day(x) { return Number.isInteger(x) ? String(x) : x.toFixed(2); }
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function pct(x) { return (100 * x).toFixed(1) + "%"; }

  // The reference each decay evaluation was judged against is written on the record itself;
  // the step line on the chart is assembled from those records, promotion by promotion.
  function referenceSteps() {
    var steps = [];
    cycles.forEach(function (c) {
      c.decay.forEach(function (d) {
        var last = steps[steps.length - 1];
        if (!last || last.ref !== d.reference_pr_auc) steps.push({ from: c.as_of_day, ref: d.reference_pr_auc, cycle: c.cycle });
      });
    });
    return steps;
  }

  // ---------- header tiles ----------
  (function tiles() {
    var h = D.headline;
    var t = [
      { label: "Shipped model, PR-AUC on the test window", value: f4(h.pr_auc.point), note: "95% bootstrap interval " + f4(h.pr_auc.low) + " to " + f4(h.pr_auc.high) + ", " + int(h.pr_auc.n_boot) + " resamples by row; ROC-AUC " + f4(h.roc_auc_test) },
      { label: "Single-row scoring latency, p50", value: f3(h.latency.p50_ms_median), unit: "ms", note: "XGBoost pinned to " + h.latency.inference_threads + " thread, median of " + h.latency.n_repeats + " repeats over " + int(h.latency.n_rows) + " rows; p99 " + f3(h.latency.p99_ms_median) + " ms" },
      { label: "Online feature store against the batch pipeline", value: h.parity.bit_identical ? "bit-identical" : f4(h.parity.max_abs_difference), note: "largest absolute difference " + h.parity.max_abs_difference + " over " + int(h.parity.n_rows) + " rows and " + h.parity.n_features + " features, " + h.parity.n_days + " days" },
      { label: "Rows replayed through the loop", value: int(D.stream.n_rows), note: D.stream.n_batches + " weekly batches, day " + day(D.stream.first_day) + " to " + day(D.stream.last_day) + "; " + int(D.stream.n_drifted_rows) + " rows carry the injected shift" }
    ];
    document.getElementById("tiles").innerHTML = t.map(function (x) {
      return '<div class="tile"><div class="label">' + esc(x.label) + '</div><div class="value">' + esc(x.value) + (x.unit ? "<small>" + x.unit + "</small>" : "") + '</div><div class="note">' + esc(x.note) + "</div></div>";
    }).join("");
  })();

  // ---------- the clock ----------
  var current = DRILL;
  var timer = null;
  var stepsEl = document.getElementById("steps");
  function stepGlyphs(i) {
    if (i === DRILL) return '<span class="g gate"></span>';
    var c = cycles[i];
    var g = [];
    if (c.drift && c.drift.drift_alert) g.push('<span class="g flag"></span>');
    if (c.decay.some(function (d) { return d.decay; })) g.push('<span class="g decay"></span>');
    if (c.challenger) g.push(c.challenger.trained ? (c.challenger.gate.promote ? '<span class="g up"></span>' : '<span class="g gate"></span>') : '<span class="g gate" style="opacity:.45"></span>');
    if (!g.length) g.push('<span class="g none"></span>');
    return g.join("");
  }
  stepsEl.innerHTML = cycles.map(function (c, i) {
    return '<button class="step" type="button" role="tab" data-i="' + i + '" aria-label="cycle ' + i + ', day ' + day(c.as_of_day) + '"><span>' + i + '</span><span class="glyphs">' + stepGlyphs(i) + "</span></button>";
  }).join("") + '<button class="step" type="button" role="tab" data-i="' + DRILL + '" aria-label="rollback drill"><span>rb</span><span class="glyphs">' + stepGlyphs(DRILL) + "</span></button>";
  stepsEl.addEventListener("click", function (e) {
    var b = e.target.closest(".step");
    if (b) { stop(); setCycle(+b.dataset.i); }
  });
  document.getElementById("prev").addEventListener("click", function () { stop(); setCycle(Math.max(0, current - 1)); });
  document.getElementById("next").addEventListener("click", function () { stop(); setCycle(Math.min(DRILL, current + 1)); });
  document.getElementById("play").addEventListener("click", function () { if (timer) stop(); else play(); });
  document.addEventListener("keydown", function (e) {
    if (e.target.tagName === "INPUT") return;
    if (e.key === "ArrowRight") { stop(); setCycle(Math.min(DRILL, current + 1)); }
    if (e.key === "ArrowLeft") { stop(); setCycle(Math.max(0, current - 1)); }
  });
  function play() {
    if (current >= DRILL) setCycle(0);
    document.getElementById("play").textContent = "Pause";
    timer = setInterval(function () {
      if (current >= DRILL) { stop(); return; }
      setCycle(current + 1);
    }, 1400);
  }
  function stop() {
    if (timer) clearInterval(timer);
    timer = null;
    document.getElementById("play").textContent = current >= DRILL ? "Replay" : "Play";
  }
  function setCycle(i) {
    current = i;
    Array.prototype.forEach.call(stepsEl.children, function (b) {
      var on = +b.dataset.i === i;
      b.classList.toggle("on", on);
      b.setAttribute("aria-selected", on ? "true" : "false");
    });
    var r = document.getElementById("readout");
    if (i === DRILL) r.innerHTML = "<b>rollback drill</b> after cycle " + (N - 1);
    else r.innerHTML = "cycle <b>" + i + "</b> day <b>" + day(cycles[i].as_of_day) + "</b>";
    document.getElementById("play").textContent = timer ? "Pause" : (i >= DRILL ? "Replay" : "Play");
    revealChart(i);
    renderConsole(i);
  }

  // ---------- the chart: three lanes on one clock ----------
  var W = 760, PADL = 52, PADR = 18;
  var X0 = 120, X1 = 222;
  var laneA = { top: 30, h: 150 }, laneG = { top: 206, h: 44 }, laneB = { top: 280, h: 190 };
  var H = laneB.top + laneB.h + 34;
  function sx(d) { return PADL + (d - X0) / (X1 - X0) * (W - PADL - PADR); }
  function syA(v) { return laneA.top + laneA.h - (v / 2.2) * laneA.h; }
  function syB(v) { return laneB.top + laneB.h - ((v - 0.1) / (0.85 - 0.1)) * laneB.h; }
  var chartEl = document.getElementById("chart");
  var tipEl = document.getElementById("tip");
  var marks = [];

  function buildChart() {
    var s = [];
    s.push('<svg viewBox="0 0 ' + W + " " + H + '" role="img" aria-label="the drift job, the gate and the decay job per cycle on one clock">');
    // grids and axes
    [0, 0.5, 1.0, 1.5, 2.0].forEach(function (v) {
      s.push('<line class="grid" x1="' + PADL + '" x2="' + (W - PADR) + '" y1="' + syA(v) + '" y2="' + syA(v) + '"/>');
      s.push('<text class="mono" x="' + (PADL - 8) + '" y="' + (syA(v) + 4) + '" text-anchor="end">' + f2(v) + "</text>");
    });
    [0.2, 0.4, 0.6, 0.8].forEach(function (v) {
      s.push('<line class="grid" x1="' + PADL + '" x2="' + (W - PADR) + '" y1="' + syB(v) + '" y2="' + syB(v) + '"/>');
      s.push('<text class="mono" x="' + (PADL - 8) + '" y="' + (syB(v) + 4) + '" text-anchor="end">' + f2(v) + "</text>");
    });
    for (var dd = 120; dd <= 220; dd += 20) {
      s.push('<line class="axis" x1="' + sx(dd) + '" x2="' + sx(dd) + '" y1="' + (laneB.top + laneB.h) + '" y2="' + (laneB.top + laneB.h + 5) + '"/>');
      s.push('<text class="mono" x="' + sx(dd) + '" y="' + (laneB.top + laneB.h + 18) + '" text-anchor="middle">' + dd + "</text>");
    }
    s.push('<text class="lab" x="' + (W - PADR) + '" y="' + (laneB.top + laneB.h + 31) + '" text-anchor="end">day of the clock, TransactionDT / 86,400</text>');
    s.push('<text class="lab" x="' + PADL + '" y="' + (laneA.top - 12) + '">drift job at each batch close, labels not read: score PSI</text>');
    s.push('<text class="lab" x="' + PADL + '" y="' + (laneG.top - 8) + '">the decision and the gate</text>');
    s.push('<text class="lab" x="' + PADL + '" y="' + (laneB.top - 12) + '">decay job when a batch&rsquo;s labels mature, ' + D.inputs.maturity_days + ' days after it closes: PR-AUC</text>');
    // the shipped model's score edge and the injection
    s.push('<line x1="' + PADL + '" x2="' + (W - PADR) + '" y1="' + syA(EDGE0) + '" y2="' + syA(EDGE0) + '" stroke="var(--crit)" stroke-width="1.2" opacity="0.8"/>');
    s.push('<text class="mono" x="' + (W - PADR) + '" y="' + (syA(EDGE0) - 5) + '" text-anchor="end">edge ' + f2(EDGE0) + "</text>");
    s.push('<line x1="' + sx(INJECT) + '" x2="' + sx(INJECT) + '" y1="' + (laneA.top - 2) + '" y2="' + (laneB.top + laneB.h) + '" stroke="var(--ink-3)" stroke-width="1" stroke-dasharray="3 3"/>');
    s.push('<text class="lab" x="' + (sx(INJECT) - 6) + '" y="' + (laneA.top + 12) + '" text-anchor="end">drift injected, day ' + day(INJECT) + "</text>");
    // lane A: score PSI per cycle
    var prev = null;
    cycles.forEach(function (c) {
      if (!c.drift) return;
      var x = sx(c.as_of_day), y = syA(c.drift.score_psi);
      if (prev) s.push('<line class="rev" data-c="' + c.cycle + '" x1="' + prev.x + '" y1="' + prev.y + '" x2="' + x + '" y2="' + y + '" stroke="var(--blue)" stroke-width="2" stroke-linecap="round"/>');
      prev = { x: x, y: y };
    });
    var prevCount = null;
    cycles.forEach(function (c) {
      if (!c.drift) return;
      var x = sx(c.as_of_day), y = syA(c.drift.score_psi);
      var tip = "cycle " + c.cycle + ", day " + day(c.as_of_day) + "\nbatch " + c.drift.batch + ", " + int(c.drift.n_rows) + " rows\nscore PSI " + f4(c.drift.score_psi) + "\n" + c.drift.n_alert + " columns past their edge\n" + (c.drift.drift_alert ? "flag raised" : "no flag");
      s.push('<g class="mark rev" data-c="' + c.cycle + '" data-tip="' + esc(tip) + '" tabindex="0"><circle cx="' + x + '" cy="' + y + '" r="11" fill="transparent"/><circle cx="' + x + '" cy="' + y + '" r="5.5" fill="var(--surface)"/><circle cx="' + x + '" cy="' + y + '" r="4" fill="' + (c.drift.drift_alert ? "var(--crit)" : "var(--blue)") + '"/></g>');
      if (c.drift.n_alert !== prevCount) s.push('<text class="mono rev" data-c="' + c.cycle + '" x="' + x + '" y="' + (y - 11) + '" text-anchor="middle">' + c.drift.n_alert + " col past edge</text>");
      prevCount = c.drift.n_alert;
    });
    // lane G: decisions and gate verdicts
    var gy = laneG.top + laneG.h / 2;
    s.push('<line class="axis" x1="' + PADL + '" x2="' + (W - PADR) + '" y1="' + gy + '" y2="' + gy + '"/>');
    cycles.forEach(function (c) {
      var ch = c.challenger;
      if (!ch) return;
      var x = sx(c.as_of_day);
      if (!ch.trained) {
        s.push('<g class="mark rev" data-c="' + c.cycle + '" data-tip="' + esc("cycle " + c.cycle + ": retrain on " + c.decision.reason.replace("_", " ") + "\nno challenger: " + ch.reason) + '" tabindex="0"><circle cx="' + x + '" cy="' + gy + '" r="11" fill="transparent"/><circle cx="' + x + '" cy="' + gy + '" r="4.5" fill="var(--surface)" stroke="var(--ink-3)" stroke-width="1.5"/></g>');
        return;
      }
      var up = ch.gate.promote;
      var tri = up ? (x + "," + (gy - 6) + " " + (x - 6) + "," + (gy + 5) + " " + (x + 6) + "," + (gy + 5)) : (x + "," + (gy + 6) + " " + (x - 6) + "," + (gy - 5) + " " + (x + 6) + "," + (gy - 5));
      var tip = "cycle " + c.cycle + ": challenger " + ch.number + " at the gate\n" + f4(ch.gate.champion.point) + " champion vs " + f4(ch.gate.challenger.point) + " challenger\ndifference " + sg(ch.gate.difference.point) + " (" + sg(ch.gate.difference.low) + " to " + sg(ch.gate.difference.high) + ")\n" + ch.gate.reason;
      s.push('<g class="mark rev" data-c="' + c.cycle + '" data-tip="' + esc(tip) + '" tabindex="0"><circle cx="' + x + '" cy="' + gy + '" r="12" fill="transparent"/><polygon points="' + tri + '" fill="' + (up ? "var(--good)" : "var(--ink-3)") + '"/></g>');
      s.push('<text class="lab rev" data-c="' + c.cycle + '" x="' + x + '" y="' + (gy + (up ? 19 : -11)) + '" text-anchor="middle">' + (up ? "promoted" : "refused") + "</text>");
    });
    // lane B: the reference steps, the tolerance, and each matured batch
    var steps = referenceSteps();
    steps.forEach(function (st, i) {
      var xa = sx(Math.max(X0, st.from - 4)), xb = i + 1 < steps.length ? sx(steps[i + 1].from - 4) : sx(X1);
      s.push('<line class="rev" data-c="' + st.cycle + '" x1="' + xa + '" x2="' + xb + '" y1="' + syB(st.ref) + '" y2="' + syB(st.ref) + '" stroke="var(--ink-3)" stroke-width="1.3"/>');
      s.push('<line class="rev" data-c="' + st.cycle + '" x1="' + xa + '" x2="' + xb + '" y1="' + syB(st.ref - TOL) + '" y2="' + syB(st.ref - TOL) + '" stroke="var(--crit)" stroke-width="1.2" opacity="0.8"/>');
      if (i + 1 < steps.length) {
        s.push('<line class="rev" data-c="' + steps[i + 1].cycle + '" x1="' + xb + '" x2="' + xb + '" y1="' + syB(st.ref) + '" y2="' + syB(steps[i + 1].ref) + '" stroke="var(--ink-3)" stroke-width="1.3"/>');
        s.push('<line class="rev" data-c="' + steps[i + 1].cycle + '" x1="' + xb + '" x2="' + xb + '" y1="' + syB(st.ref - TOL) + '" y2="' + syB(steps[i + 1].ref - TOL) + '" stroke="var(--crit)" stroke-width="1.2" opacity="0.8"/>');
      }
      s.push('<text class="mono rev" data-c="' + st.cycle + '" x="' + (xa + 4) + '" y="' + (syB(st.ref) - 4) + '">ref ' + f4(st.ref) + "</text>");
    });
    cycles.forEach(function (c) {
      c.decay.forEach(function (d) {
        var x = sx(c.as_of_day), y = syB(d.pr_auc);
        var col = d.decay ? "var(--crit)" : "var(--blue)";
        var tip = "cycle " + c.cycle + ", day " + day(c.as_of_day) + ": batch " + d.batch + " matured\nPR-AUC " + f4(d.pr_auc) + " (" + f4(d.pr_auc_low) + " to " + f4(d.pr_auc_high) + ")\nreference " + f4(d.reference_pr_auc) + ", drop " + sg(d.drop) + "\n" + (d.decay ? "decay: the drop clears the tolerance" : "no decay") + "\n" + int(d.drifted_rows) + " of " + int(d.n_rows) + " rows drifted";
        s.push('<g class="mark rev" data-c="' + c.cycle + '" data-tip="' + esc(tip) + '" tabindex="0"><rect x="' + (x - 11) + '" y="' + (syB(d.pr_auc_high) - 4) + '" width="22" height="' + (syB(d.pr_auc_low) - syB(d.pr_auc_high) + 8) + '" fill="transparent"/><line x1="' + x + '" x2="' + x + '" y1="' + syB(d.pr_auc_low) + '" y2="' + syB(d.pr_auc_high) + '" stroke="' + col + '" stroke-width="2" stroke-linecap="round"/><circle cx="' + x + '" cy="' + y + '" r="5.5" fill="var(--surface)"/><circle cx="' + x + '" cy="' + y + '" r="4" fill="' + col + '"/></g>');
        if (d.decay) s.push('<text class="mono rev" data-c="' + c.cycle + '" x="' + x + '" y="' + (syB(d.pr_auc_low) + 14) + '" text-anchor="middle">batch ' + d.batch + "</text>");
      });
    });
    s.push('<line id="cursor" class="cursor" x1="0" x2="0" y1="' + (laneA.top - 2) + '" y2="' + (laneB.top + laneB.h) + '" opacity="0"/>');
    s.push("</svg>");
    chartEl.innerHTML = s.join("");
    marks = Array.prototype.slice.call(chartEl.querySelectorAll(".mark"));
    marks.forEach(function (m) {
      m.addEventListener("mouseenter", function () { showTip(m); });
      m.addEventListener("focus", function () { showTip(m); });
      m.addEventListener("mouseleave", hideTip);
      m.addEventListener("blur", hideTip);
      m.addEventListener("click", function () { stop(); setCycle(+m.dataset.c); });
    });
  }
  function showTip(m) {
    var box = chartEl.getBoundingClientRect();
    var r = m.getBoundingClientRect();
    tipEl.textContent = m.dataset.tip;
    tipEl.style.left = (r.left + r.width / 2 - box.left) + "px";
    tipEl.style.top = (r.top - box.top) + "px";
    tipEl.classList.add("show");
  }
  function hideTip() { tipEl.classList.remove("show"); }
  function revealChart(i) {
    var upto = i === DRILL ? N - 1 : i;
    Array.prototype.forEach.call(chartEl.querySelectorAll(".rev"), function (el) {
      el.classList.toggle("future", +el.dataset.c > upto);
    });
    var cur = document.getElementById("cursor");
    if (i === DRILL) { cur.setAttribute("opacity", "0"); }
    else {
      var x = sx(cycles[i].as_of_day);
      cur.setAttribute("x1", x); cur.setAttribute("x2", x); cur.setAttribute("opacity", "0.7");
    }
    document.getElementById("chart-title").textContent = i === DRILL ? "The whole run, then the drill: one step back through the registry" : "What the jobs had seen by cycle " + i + ", day " + day(cycles[i].as_of_day);
  }

  // ---------- the console ----------
  function gateLine(g) {
    var lo = -0.09, hi = 0.15, w = 300, h = 46, pl = 8, pr = 8;
    function gx(v) { return pl + (v - lo) / (hi - lo) * (w - pl - pr); }
    var y = 26;
    var s = '<svg viewBox="0 0 ' + w + " " + h + '" aria-label="the challenger&rsquo;s advantage against the margin">';
    s += '<line x1="' + pl + '" x2="' + (w - pr) + '" y1="' + y + '" y2="' + y + '" stroke="var(--line-2)" stroke-width="1"/>';
    [0, MARGIN].forEach(function (v) {
      s += '<line x1="' + gx(v) + '" x2="' + gx(v) + '" y1="' + (y - 9) + '" y2="' + (y + 9) + '" stroke="' + (v === 0 ? "var(--ink-3)" : "var(--good)") + '" stroke-width="1.4"/>';
      s += '<text class="mono" x="' + gx(v) + '" y="' + (y + 20) + '" text-anchor="middle" style="font-size:10px">' + (v === 0 ? "0" : "margin " + f2(v)) + "</text>";
    });
    var col = g.promote ? "var(--good)" : (g.above_noise ? "var(--warn)" : "var(--crit)");
    s += '<line x1="' + gx(g.difference.low) + '" x2="' + gx(g.difference.high) + '" y1="' + y + '" y2="' + y + '" stroke="' + col + '" stroke-width="4" stroke-linecap="round"/>';
    s += '<circle cx="' + gx(g.difference.point) + '" cy="' + y + '" r="5.5" fill="var(--surface)"/><circle cx="' + gx(g.difference.point) + '" cy="' + y + '" r="4" fill="' + col + '"/>';
    s += '<text class="mono" x="' + gx(g.difference.point) + '" y="' + (y - 13) + '" text-anchor="middle" style="font-size:10.5px;fill:var(--ink)">' + sg(g.difference.point) + "</text>";
    s += "</svg>";
    return s;
  }
  function pill(cls, text) { return '<span class="pill ' + cls + '">' + esc(text) + "</span>"; }
  function kv(rows) {
    return '<dl class="kv">' + rows.map(function (r) { return "<dt>" + esc(r[0]) + '</dt><dd class="' + (r[2] || "") + '">' + r[1] + "</dd>"; }).join("") + "</dl>";
  }

  function renderConsole(i) {
    var out = [];
    if (i === DRILL) {
      var rb = D.rollback, ab = rb.aliases_before, aa = rb.aliases_after;
      out.push('<div class="card"><div class="head"><h3>Rollback drill</h3>' + pill("blue", "performed") + "</div>" +
        '<p class="quiet" style="margin-bottom:8px">' + esc(rb.what) + ". The production alias moves back to the previous version.</p>" +
        kv([
          ["production before", "version " + ab.production],
          ["previous before", "version " + ab.previous],
          ["production after", "version " + aa.production],
          ["rolled-back after", "version " + aa["rolled-back"]],
          ["loaded through", esc(rb.loaded.uri) + " (version " + rb.loaded.version + ", " + rb.loaded.n_columns + " columns)"],
          ["served vs batch", "largest absolute score difference " + rb.smoke.max_abs_score_difference_serving_vs_batch + " over " + int(rb.smoke.n_rows) + " rows"]
        ]) + "</div>");
      out.push('<div class="card"><div class="head"><h3>Where the run ended</h3></div>' + kv([
        ["cycles", String(N)],
        ["challengers fitted", String(D.cycles.filter(function (c) { return c.challenger && c.challenger.trained; }).length)],
        ["promotions", String(D.cycles.filter(function (c) { return c.challenger && c.challenger.promotion; }).length)],
        ["production at the end", "version " + aa.production + " after the drill, version " + ab.production + " before it"],
        ["reference at the end", f4(D.promotion.new_reference_pr_auc) + " (was " + f4(REF0) + ")"],
        ["run time", Math.round(D.run.seconds) + " seconds, seed " + D.run.seed]
      ]) + "</div>");
      document.getElementById("console").innerHTML = out.join("");
      return;
    }
    var c = cycles[i];
    // champion
    out.push('<div class="card"><div class="head"><h3>Cycle ' + c.cycle + ", day " + day(c.as_of_day) + "</h3>" + pill("blue", "production: version " + c.champion.version) + "</div>" +
      '<p class="quiet">Champion is <b>' + esc(c.champion.name) + "</b>. " + (c.drift ? "Batch " + c.drift.batch + " closed on day " + day(c.drift.end_day) + "." : "The stream has ended; the clock keeps ticking until the last batch&rsquo;s labels mature.") + "</p></div>");
    // drift job
    if (c.drift) {
      var d = c.drift;
      var top = d.top_psi.slice(0, 5);
      var mx = top[0][1];
      out.push('<div class="card"><div class="head"><h3>Drift job</h3>' + (d.drift_alert ? pill("crit", "flag raised") : pill("", "no flag")) + "</div>" +
        kv([
          ["score PSI", f4(d.score_psi) + (c.champion.version === 1 ? ' <span class="muted">edge ' + f2(EDGE0) + "</span>" : ' <span class="muted">against version ' + c.champion.version + "&rsquo;s own reference</span>")],
          ["columns past their edge", d.n_alert + ' <span class="muted">of ' + D.drift_job.n_alertable_columns + " alertable; " + d.n_alert_band + " would be in the textbook 0.20 band</span>"],
          ["rows in the batch", int(d.n_rows) + (d.drifted_rows ? ' <span class="muted">all carry the injected shift</span>' : ' <span class="muted">none drifted</span>')],
          ["labels read", "none", "text"]
        ]) +
        '<div class="bars">' + top.map(function (t) {
          return '<span>' + esc(t[0]) + '</span><div class="track"><div class="fill' + (d.drift_alert ? " crit" : "") + '" style="width:' + (100 * t[1] / mx).toFixed(1) + '%"></div></div><span class="n">' + f2(t[1]) + "</span>";
        }).join("") + "</div>" +
        '<p class="quiet" style="margin-top:8px">the five largest column PSIs; before the injection they are target encodings, which sit outside the alertable set because their PSI is high on every clean week by construction</p></div>');
    } else {
      out.push('<div class="card"><div class="head"><h3>Drift job</h3>' + pill("", "stream ended") + "</div><p class=\"quiet\">No batch closed this cycle. The drift job reads nothing.</p></div>");
    }
    // decay job
    if (c.decay.length) {
      c.decay.forEach(function (e) {
        out.push('<div class="card"><div class="head"><h3>Decay job: batch ' + e.batch + " matured</h3>" + (e.decay ? pill("crit", "decay") : pill("good", "no decay")) + "</div>" +
          kv([
            ["PR-AUC", f4(e.pr_auc) + ' <span class="muted">' + f4(e.pr_auc_low) + " to " + f4(e.pr_auc_high) + "</span>"],
            ["reference", f4(e.reference_pr_auc) + ' <span class="muted">tolerance ' + f2(TOL) + "</span>"],
            ["drop", sg(e.drop) + ' <span class="muted">lower bound ' + sg(e.drop_low) + "</span>"],
            ["precision, recall", f4(e.precision) + ", " + f4(e.recall)],
            ["rows, fraud", int(e.n_rows) + ", " + int(e.n_fraud) + (e.drifted_rows ? ' <span class="muted">drifted</span>' : ' <span class="muted">clean</span>')],
            ["labels read", "batch " + e.batch + " only, closed day " + day(e.end_day) + ", matured day " + day(e.matured_at_day), "text"]
          ]) + "</div>");
      });
    } else {
      out.push('<div class="card"><div class="head"><h3>Decay job</h3>' + pill("", "nothing mature") + '</div><p class="quiet">No batch has had its labels for ' + D.inputs.maturity_days + " days yet. The job reads no labels and writes nothing.</p>" +
        '<div class="chip-row">' + c.immature.map(function (b) { return '<span class="chip">b' + b + "</span>"; }).join("") + "</div></div>");
    }
    // decision
    var dec = c.decision;
    var decPill = dec.retrain ? pill("crit", "retrain: " + dec.reason.replace("_", " ")) : pill("", "no retrain");
    out.push('<div class="card"><div class="head"><h3>should_retrain()</h3>' + decPill + "</div>" +
      kv([
        ["latest decay verdict", dec.latest_decay === null ? '<span class="muted">none yet</span>' : (dec.latest_decay ? "decay" : "no decay"), "text"],
        ["consecutive drift flags", dec.consecutive_drift_alerts + ' <span class="muted">sustained at ' + dec.sustained_cycles + "</span>"],
        ["rule", "decay is the primary trigger; " + dec.sustained_cycles + " consecutive flags the early one", "text"]
      ]) + "</div>");
    // challenger and gate
    var ch = c.challenger;
    if (ch && !ch.trained) {
      out.push('<div class="card"><div class="head"><h3>Challenger</h3>' + pill("warn", "not fitted") + '</div><p class="quiet">' + esc(ch.reason) + ". Mature data ends on day " + day(ch.mature_end_day) + "; the gate window would start on day " + day(ch.gate_start_day) + ", inside the champion&rsquo;s training window, which ends on day " + day(ch.champion_train_end_day) + ".</p></div>");
    } else if (ch) {
      var g = ch.gate, w = ch.windows, fit = ch.fit;
      var verdictPill = g.promote ? pill("good", "promoted") : pill(g.above_noise ? "warn" : "crit", "refused");
      out.push('<div class="card"><div class="head"><h3>Challenger ' + ch.number + " at the gate</h3>" + verdictPill + "</div>" +
        kv([
          ["trigger", ch.trigger.replace("_", " "), "text"],
          ["fit window", "day " + day(w.fit_start_dt) + " to " + day(w.fit_end_dt) + ' <span class="muted">' + int(fit.n_fit_rows) + " rows, " + int(ch.drifted_rows_in_fit_window) + " drifted</span>"],
          ["calibration, gate", "day " + day(w.calibration_start_dt) + " to " + day(w.calibration_end_dt) + ", " + day(w.gate_start_dt) + " to " + day(w.gate_end_dt)],
          ["gate rows", int(ch.gate_rows) + ' <span class="muted">' + int(ch.gate_drifted_rows) + " drifted, " + int(ch.gate_fraud) + " fraud</span>"],
          ["champion", f4(g.champion.point) + ' <span class="muted">' + f4(g.champion.low) + " to " + f4(g.champion.high) + "</span>"],
          ["challenger", f4(g.challenger.point) + ' <span class="muted">' + f4(g.challenger.low) + " to " + f4(g.challenger.high) + "</span>"],
          ["difference", sg(g.difference.point) + ' <span class="muted">' + sg(g.difference.low) + " to " + sg(g.difference.high) + ", " + int(g.n_boot) + " paired resamples by card</span>"],
          ["columns", fit.n_columns + (fit.columns_dropped.length ? ' <span class="muted">dropped ' + esc(fit.columns_dropped.join(", ")) + "</span>" : "")]
        ]) +
        '<div class="gate-line">' + gateLine(g) + "</div>" +
        '<p class="verdict"><b>' + esc(g.reason) + "</b>" + (ch.promotion ? ". Production moves from version " + ch.promotion.previous + " to version " + ch.promotion.production + "; the reference becomes the challenger&rsquo;s gate PR-AUC." : ". Version " + ch.registry.version + " stays in the registry under the alias " + esc(ch.registry.alias) + ".") + "</p></div>");
    } else if (dec.retrain) {
      out.push('<div class="card"><div class="head"><h3>Challenger</h3>' + pill("", "none") + "</div></div>");
    }
    document.getElementById("console").innerHTML = out.join("");
  }

  // ---------- the ledger ----------
  (function ledger() {
    var rows = cycles.filter(function (c) { return c.challenger && c.challenger.trained; });
    var h = "<table><thead><tr><th>Cycle, day</th><th>Trigger</th><th>Gate window</th><th class=\"num\">Champion</th><th class=\"num\">Challenger</th><th class=\"num\">Difference, 95% interval</th><th>Verdict</th></tr></thead><tbody>";
    rows.forEach(function (c) {
      var ch = c.challenger, g = ch.gate, w = ch.windows;
      h += "<tr><td>" + c.cycle + ", " + day(c.as_of_day) + "</td><td>" + esc(ch.trigger.replace("_", " ")) + "</td><td>day " + day(w.gate_start_dt) + " to " + day(w.gate_end_dt) + '<br><span class="muted">' + int(ch.gate_drifted_rows) + " of " + int(ch.gate_rows) + " rows drifted</span></td>" +
        '<td class="num">' + f4(g.champion.point) + '</td><td class="num">' + f4(g.challenger.point) + '</td><td class="num">' + sg(g.difference.point) + '<br><span class="muted">' + sg(g.difference.low) + " to " + sg(g.difference.high) + "</span></td>" +
        "<td>" + (g.promote ? pill("good", "promoted") : pill(g.above_noise ? "warn" : "crit", "refused")) + '<br><span class="muted">' + esc(g.reason.replace(/^(promoted|refused): /, "")) + (ch.promotion ? "; production " + ch.promotion.previous + " to " + ch.promotion.production : "") + "</span></td></tr>";
    });
    h += "</tbody></table>";
    document.getElementById("ledger").innerHTML = h;
  })();

  // ---------- inputs ----------
  (function inputs() {
    var dj = D.drift_job, dk = D.decay_job, nb = D.noise_band, inp = D.inputs;
    var tb = dj.textbook_alert_band_per_batch;
    var cards = [
      '<div class="card"><h3>Promotion margin</h3><p class="big">' + f2(MARGIN) + "</p><p>The widest paired 95% bootstrap half-width stage 6 measured on the test PR-AUC, over every pair of its ten candidate models, rounded up at the second decimal. The card resample is the wider of the two and respects card-level labels, so it is the band.</p>" +
        '<pre class="arith">by row   ' + f4(nb.by_row.half_width) + "  " + esc(nb.by_row.pair.join(" vs ")) + "\nby card  " + f4(nb.by_card.half_width) + "  " + esc(nb.by_card.pair.join(" vs ")) + "\nmargin   " + f4(nb.by_card.half_width) + " rounded up at 2 dp = " + f2(MARGIN) + "</pre>" +
        "<p style=\"margin-top:8px\">The decay tolerance is the margin: a drop the gate could not act on is not a reason to retrain. On the " + dk.n_batches + " in-control weeks the largest drop was " + f4(dk.largest_drop) + ", headroom " + f4(dk.headroom) + ".</p></div>",
      '<div class="card"><h3>Drift edges</h3><p class="big">' + f2(dj.score_alert_edge) + " score, &gt; " + dj.feature_count_edge + " column" + (dj.feature_count_edge === 1 ? "" : "s") + "</p><p>Calibrated on " + dj.n_batches + " in-control weekly batches of " + dj.n_columns + " columns, " + dj.n_alertable_columns + " of them alertable. A column's edge is the larger of 0.20 and the worst PSI it showed on a clean week, and it alerts strictly above it; a batch flags on the score PSI past its edge or on more columns past theirs than any clean week put past theirs when held out.</p>" +
        "<p>Held out one week at a time, that count was at most " + dj.feature_count_edge + " column, which is where the batch edge sits.</p>" +
        "<p>The textbook 0.20 band would have put " + Math.min.apply(null, tb) + " to " + Math.max.apply(null, tb) + " columns in alert on every one of those clean weeks; the calibrated rule flagged none, and held out one week at a time it flagged none (rate " + dj.leave_one_out_rate_any_alert + ").</p>" +
        "<p>Sustained drift is " + inp.sustained_cycles + " consecutive flagged cycles: the smallest run that is not a spike. The longest run on the clean weeks was " + dj.longest_run_of_drift_alerts + ".</p></div>",
      '<div class="card"><h3>The clocks and the shift</h3><p class="big">' + inp.batch_days + " day batches, " + inp.maturity_days + " day maturity</p><p>Both are inputs, not measurements: an earlier stage swept the label delay from 15 to 90 days and found nothing in this file that says where the true chargeback delay sits.</p>" +
        "<p>Challenger windows " + inp.challenger_windows.fit_days + ", " + inp.challenger_windows.calibration_days + " and " + inp.challenger_windows.gate_days + " days: fit, calibration, gate. The stream is " + esc(inp.stream) + ".</p>" +
        "<p>From day " + day(inp.drift_from_day) + " (batch " + inp.drift_from_batch + "): " + esc(inp.injection.amount) + ", " + esc(inp.injection.counts) + ", " + esc(inp.injection.applied_to) + ".</p></div>"
    ];
    document.getElementById("inputs-grid").innerHTML = cards.join("");
  })();

  // ---------- drift character ----------
  (function character() {
    var a = D.adversarial, full = a.fits.full, wo = a.fits.without_target_encodings, woc = a.fits.without_entity_and_clock;
    var left = '<div class="card"><h3>Three fits, train against test</h3>' + kv([
      ["all " + full.n_columns + " columns", "AUC " + f4(full.auc_out_of_fold) + ' <span class="muted">top 10 gain ' + pct(full.entity_and_clock_share_of_top_10_gain) + " on who-and-when columns</span>"],
      ["without the target encodings", "AUC " + f4(wo.auc_out_of_fold) + ' <span class="muted">' + wo.n_columns + " columns, " + pct(wo.entity_and_clock_share_of_top_10_gain) + "</span>"],
      ["without identifiers, their encodings and the timedeltas", "AUC " + f4(woc.auc_out_of_fold) + ' <span class="muted">' + woc.n_columns + " columns</span>"]
    ]) + '<p class="quiet" style="margin-top:10px">Out-of-fold AUC of a classifier separating ' + int(a.n_train_rows) + " train rows from " + int(a.n_test_rows) + " test rows. The target encodings separate the windows by construction: on test they take a handful of frozen values the training-time smear never lands on exactly, a fact about how they are computed, not about the cards. Set them aside and the shift reads as population turnover and the calendar: days-since counters that grow for every returning card, an identity attribute whose value mix changed, and the frequency of card identifiers. It is not a change in what fraud looks like. Spearman between a column&rsquo;s gain here and its stage 2 train-to-test PSI over the 59 raw columns both hold: " + f3(a.spearman_gain_vs_stage_2_psi) + "; the two rankings agree.</p></div>";
    var mx = wo.top[0].gain_share;
    var right = '<div class="card"><h3>Top ten without the target encodings</h3><div class="bars">' + wo.top.map(function (t) {
      return "<span>" + esc(t.column) + '</span><div class="track"><div class="fill" style="width:' + (100 * t.gain_share / mx).toFixed(1) + '%"></div></div><span class="n">' + pct(t.gain_share) + '</span>';
    }).join("") + '</div><p class="quiet" style="margin-top:10px">share of the classifier&rsquo;s gain; groups: ' + esc(wo.top.map(function (t) { return t.column + " (" + t.group.replace(/_/g, " ") + ")"; }).join(", ")) + "</p></div>";
    document.getElementById("character-grid").innerHTML = left + right;
  })();

  // ---------- what is not established ----------
  (function notEstablished() {
    var gates = cycles.filter(function (c) { return c.challenger && c.challenger.trained; });
    var nearest = null;
    gates.forEach(function (c) {
      var dist = Math.abs(c.challenger.gate.difference.point - MARGIN);
      if (!nearest || dist < nearest.dist) nearest = { c: c, dist: dist, hw: c.challenger.gate.difference.half_width };
    });
    var fitDrifted = gates.map(function (c) { return c.challenger.drifted_rows_in_fit_window; });
    var items = [
      "<strong>Whether the gate was exercised near its margin.</strong> Once, and not firmly: the cycle " + nearest.c.cycle + " verdict cleared " + f2(MARGIN) + " by " + f4(nearest.dist) + ", inside that pair&rsquo;s own half-width of " + f4(nearest.hw) + ". The other three verdicts sat well away from the margin on either side. One near-margin decision on one seed says nothing about the gate&rsquo;s behaviour at the margin.",
      "<strong>Whether sustained drift was observed or synthesised.</strong> The cycles are real consecutive weeks and no row was replayed; the drift itself is a transformation applied to real rows from a chosen day. On the file&rsquo;s own clean weeks the flag never rose, so sustained drift of the file&rsquo;s own making was not observed.",
      "<strong>Whether a challenger learned the shift.</strong> None did: every fit window ended before day " + day(INJECT) + " (drifted rows in the fit windows: " + fitDrifted.join(", ") + "), because " + D.inputs.maturity_days + " days of maturity plus " + (D.inputs.challenger_windows.calibration_days + D.inputs.challenger_windows.gate_days) + " days of calibration and gate windows consumed every mature drifted row. The promoted models won on drifted gate windows by being less damaged than the champion, not by having seen the change.",
      "<strong>Whether the lifecycle holds an absolute standard.</strong> It does not. The reference moves to the promoted model&rsquo;s gate PR-AUC, so after the last promotion the bar is " + f4(D.promotion.new_reference_pr_auc) + " while the shipped model was accepted at " + f4(REF0) + ". The design as built ratchets; a floor is a design not written.",
      "<strong>A promoted model&rsquo;s drift reference.</strong> It is calibrated on the batches of its own calibration and gate windows, which hold drifted rows, so its edges absorb the shift it was promoted under: the last promoted model&rsquo;s score edge is " + f4(D.promotion.new_drift_reference.score_alert_edge) + " and its count edge " + D.promotion.new_drift_reference.feature_count_edge + ", against " + f2(EDGE0) + " and " + D.champion.drift_reference.feature_count_edge + " for the shipped model on " + D.champion.drift_reference.n_calibration_batches + " clean weeks.",
      "<strong>The true chargeback delay, the batch length, the window lengths.</strong> All inputs; the artifact labels them."
    ];
    document.getElementById("not-list").innerHTML = items.map(function (t) { return "<li>" + t + "</li>"; }).join("");
  })();

  // ---------- sources ----------
  (function sources() {
    var feeds = {
      "reports/lifecycle_demo.json": "the run: every cycle, verdict, alias move and the drill",
      "reports/monitoring/drift.json": "the drift edges and the in-control weeks",
      "reports/monitoring/decay.json": "the decay reference, tolerance and headroom",
      "reports/adversarial_validation.json": "the three adversarial fits and the top columns",
      "reports/metric_variance.json": "the shipped model&rsquo;s interval and the noise band",
      "reports/operating_points.json": "ROC-AUC on test",
      "reports/latency.json": "single-row latency",
      "reports/parity.json": "online against batch features",
      "reports/split_summary.json": "row counts"
    };
    var h = "<table><thead><tr><th>Artifact</th><th>Feeds</th><th>Regenerate with</th><th>Commit</th></tr></thead><tbody>";
    D.sources.forEach(function (s) {
      h += '<tr><td class="mono">' + esc(s.artifact) + "</td><td>" + esc(feeds[s.artifact] || "") + '</td><td class="mono">' + esc((s.regenerate_with || "").split("  #")[0]) + '</td><td class="mono">' + esc((s.git_commit || "").slice(0, 7)) + "</td></tr>";
    });
    h += '<tr><td class="mono">docs/demo/index.html</td><td>this page</td><td class="mono">make demo-page</td><td class="mono"></td></tr>';
    h += "</tbody></table>";
    document.getElementById("sources-table").innerHTML = h;
    var env = D.run.environment;
    document.getElementById("foot").innerHTML = "lifecycle run " + esc(D.run.generated_at_utc) + ", commit " + esc(D.run.git_commit.slice(0, 7)) + ", seed " + D.run.seed + ", " + Math.round(D.run.seconds) + " s on " + esc(env.platform) + "<br>python " + esc(env.python) + ", pandas " + esc(env.pandas) + ", numpy " + esc(env.numpy) + ", scikit-learn " + esc(env.scikit_learn) + ", xgboost " + esc(env.xgboost) + ", mlflow " + esc(env.mlflow) + "<br>no data ships with this page; the IEEE-CIS files are under Kaggle competition rules";
  })();

  buildChart();
  setCycle(DRILL);
})();
</script>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--reports-dir", type=Path, default=Path("reports"))
    parser.add_argument("--out", type=Path, default=OUT_DEFAULT)
    args = parser.parse_args()
    data = extract(args.reports_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(data), encoding="utf-8")
    print(
        f"wrote {args.out} ({args.out.stat().st_size:,} bytes): "
        f"{len(data['cycles'])} cycles from {data['sources'][0]['artifact']}"
    )


if __name__ == "__main__":
    main()
